on: push
name: deploy
jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar herramientas de estilo
        run: pip install flake8 black

      - name: Verificar estilo de código
        run: |
          flake8 --exclude=.venv
          black --check .